# Generated by Django 2.2 on 2019-04-17 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='tel',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
